name: Release Approval Workflow

on:
  release:
    types: [published]
    
permissions:
  issues: write

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1.9.1
        with:
          secret: ${{ github.TOKEN }}
          approvers: linchpincafe
          minimum-approvals: 1
          issue-title: "Deploying ${{ github.ref }} to prod from staging"
          issue-body: "Please approve or deny the deployment of version ${{ github.ref }}"

      - name: Get approval result
        run: echo "Approval result ${{ steps.approval.outputs.result }}"
        env:
          APPROVAL_RESULT: ${{ steps.approval.outputs.result }}

      - name: Process approval result
        run: |
          if [ "${{ env.APPROVAL_RESULT }}" == "approve" ]; then
            echo "Workflow approved"
            # Add your approval logic here
          else
            echo "Workflow denied"
            # Add your denial logic here
          fi
          echo "Issue number ${{ github.event.issue.number }}"
          echo "Release tag ${{ github.ref }}"
