name: Release Approval Workflow

on:
  release:
    types: [published]
    
permissions:
  issues: write

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Manual Workflow Approval
        id: approval
        uses: trstringer/manual-approval@v1.9.1
        with:
          secret: ${{ github.TOKEN }}
          approvers: linchpincafe
          minimum-approvals: 1
          issue-title: "Deploying ${{ github.ref }} to prod from staging"
          issue-body: "Please approve or deny the deployment of version ${{ github.ref }}"

      - name: Deploy to Production
        if: success()
        run: |
          echo "Deploying to production..."
          echo "Issue number ${{ github.event.issue.number }}"
          echo "Release tag ${{ github.ref }}"
          # Add your deployment script here
