name: Release Approval Workflow

on:
  release:
    types: [published]

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1.9.1
        with:
          secret: ${{ github.TOKEN }}
          approvers: linchpincafe
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

      - name: Continue if approved
        if: ${{ steps.approval.outputs.approved == 'true' }}
        run: echo "Release approved and continuing with deployment..."
