name: Release Approval Workflow

on:
  release:
    types: [published]
    
permissions:
  issues: write

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Manual Workflow Approval
        id: approval
        uses: trstringer/manual-approval@v1.9.1
        with:
          secret: ${{ github.TOKEN }}
          approvers: linchpincafe
          minimum-approvals: 1
          issue-title: "Deploying ${{ github.ref }} to prod from staging"
          issue-body: "Please approve or deny the deployment of version ${{ github.ref }}"

      - name: Deploy to Production
        if: success()
        run: |
          echo "Deploying to production..."
          echo "Issue number ${{ github.event.issue.number }}"
          echo "Release tag ${{ github.ref }}"
          # echo "${{ github.ref }}" >> approved
          # Add your deployment script here

      - name: Set up Git configuration
        run: |
          git config --global user.name 'linchpincafe'
          git config --global user.email 'puwangster@hotmail.com'
          git config --global credential.helper store
          echo "https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com" > ~/.git-credentials
  
      - name: Make changes to a file
        run: |
          echo "${{ github.ref }}" >> approved
  
      - name: Commit and push changes
        run: |
          git add approved
          git commit -m "Update approved with new changes"
          git push origin HEAD:refs/heads/main
          

