name: Release Approval Workflow

on:
  release:
    types: [published]
    
permissions:
  issues: write

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1.9.1
        with:
          secret: ${{ github.TOKEN }}
          approvers: linchpincafe
          minimum-approvals: 1
          issue-title: "Deploying ${{ github.ref }} to prod from staging"
          issue-body: "Please approve or deny the deployment of version ${{ github.ref }}"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

      - name: Get Issue Number
        run: echo "Issue number ${{ github.event.issue.number }}"
      - run: echo "Release tag ${{ github.ref }}"
        
      - name: Continue if approved
        if: ${{ steps.approval.outputs.approved == 'true' }}
        run: echo "Release approved and continuing with deployment..."
